// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.layout.display-list.retain", true);
user_pref("app.normandy.startupRolloutPrefs.security.tls.version.fallback-limit", 4);
user_pref("app.normandy.user_id", "fc8f1236-28dd-4b2c-b767-de89c13a0d43");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1544807597);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1544807717);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1544868097);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1544864737);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1544864617);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1544865609);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1544807957);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1544807837);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 419840);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.ctrlTab.migrated", true);
user_pref("browser.ctrlTab.recentlyUsedOrder", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1544807205);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 76);
user_pref("browser.newtabpage.activity-stream.impressionId", "{5f172190-7436-4a0a-a6c3-3735d993e1f2}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1544824800);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\",\"webcompat-reporter_mozilla_org\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1544868132080");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1544869960080");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1544868104981");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1544871704981");
user_pref("browser.search.countryCode", "LT");
user_pref("browser.search.region", "LT");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1544865597");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20181207224003");
user_pref("browser.startup.homepage_override.mstone", "64.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\",\"feed-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1544807217380");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("devtools.performance.recording.interval", 1000);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "64.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "094d923f862d4effacec62c6958254d3");
user_pref("extensions.blocklist.lastModified", "Tue, 11 Dec 2018 16:08:04 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1544807599);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20180704192850");
user_pref("extensions.lastAppVersion", "64.0");
user_pref("extensions.lastPlatformVersion", "64.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"webcompat@mozilla.org\":\"55bdc4b4-eab7-4072-b710-8c77f9ae7bb6\",\"screenshots@mozilla.org\":\"8a388d19-534c-4527-ae11-b89a6f0b4693\",\"formautofill@mozilla.org\":\"906b5896-8975-4526-b242-f8b02a27f072\",\"webcompat-reporter@mozilla.org\":\"d715cb27-34c1-4dc8-b94d-f04719bae5f2\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1544807554);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181207224003");
user_pref("media.gmp-manager.lastCheck", 1544865764);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "92d06872-0e69-4ddb-bdbd-5210608418cf");
user_pref("security.sandbox.plugin.tempDirSuffix", "da3cf833-7822-4210-993c-c6b2e59de0d7");
user_pref("services.blocklist.addons.checked", 1544865808);
user_pref("services.blocklist.gfx.checked", 1544865808);
user_pref("services.blocklist.onecrl.checked", 1544865808);
user_pref("services.blocklist.pinning.checked", 1544865808);
user_pref("services.blocklist.plugins.checked", 1544865808);
user_pref("services.settings.clock_skew_seconds", -199);
user_pref("services.settings.last_etag", "\"1544811398633\"");
user_pref("services.settings.last_update_seconds", 1544865808);
user_pref("services.settings.main.language-dictionaries.last_check", 1544865808);
user_pref("services.settings.main.onboarding.last_check", 1544865808);
user_pref("services.settings.main.sites-classification.last_check", 1544865808);
user_pref("services.settings.main.tippytop.last_check", 1544865808);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1544865561);
user_pref("toolkit.telemetry.cachedClientID", "22013b10-c2ae-4c26-b93b-4a12fdf6ffc3");
user_pref("toolkit.telemetry.previousBuildID", "20181207224003");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
